name: Generar Manifiesto de Posts

on:
  push:
    branches:
      - main  # ⬅️ REVISA: ¿Es 'main' o es 'master' en tu repo?
    paths:
      - 'posts/*.md' # ⬅️ REVISA: Asegúrate de que la carpeta se llama 'posts' (minúscula)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run Manifest Generator
        run: |
          python generate_manifest.py # ⬅️ REVISA: ¿El script está en la raíz?
        
      - name: Commit and Push posts.json
        run: |
          git config user.name 'GitHub Actions Bot'
          git config user.email 'actions@github.com'
          
          if git diff --exit-code --quiet posts/posts.json; then
            echo "posts.json no ha cambiado. Terminando."
          else
            echo "Actualizando posts.json..."
            git add posts/posts.json
            git commit -m "Automatización: Actualizado posts.json [skip ci]"
            git push